language: cpp
compiler: gcc
dist: bionic

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
    packages:
    - gcc-9
    - g++-9
    - qt512base
    - qt512charts-no-lgpl
    - qt512script
    - qt512tools
    - mesa-common-dev
    - libgl1-mesa-dev
    
  coverity_scan:
    project:
      name: "darktorres/ERP-STACCATO"
      description: "ERP-STACCATO"
    notification_email: torres.dark@gmail.com
    build_command_prepend: "source /opt/qt512/bin/qt512-env.sh && /opt/qt512/bin/qmake Loja.pro"
    build_command: "make -j2"
    branch_pattern: coverity_scan
    
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then source /opt/qt512/bin/qt512-env.sh && /opt/qt512/bin/qmake Loja.pro && make -j2 ; fi